### ISSUE TITLE
Consider adding the sphinx-extension GitHub topic

### ISSUE THREAD

**Issue by jdillard** [NextThought/sphinxcontrib-programoutput#45]
Just wanted to say you should consider adding the sphinx-extension topic, https://github.com/topics/sphinx-extension, to the repo so it is easier for others to find on the GitHub ecosystem. There are currently 96 other sphinx extensions that use that topic.

**Comment by jamadden** [comment]
Thanks for the suggestion!

**Comment by ssbarnea** [comment]
That was clearly a good move. May I even suggest looking to move the extension under an organization that aims to support sphinx extensions? I do have https://github.com/sphinx-contrib in mind, mainly because I no longer want to risk adding dependencies that can become unmaintained for some reasons. I seen similar movements with pytest plugins too, as onther authors could help or even step in if main maintainer disappears.
