### ISSUE TITLE
how to use programoutput_use_ansi

### ISSUE THREAD

**Issue by shahzebsiddiqui** [NextThought/sphinxcontrib-programoutput#49]
I am looking at https://pythonhosted.org/sphinxcontrib-programoutput/#confval-programoutput_use_ansi but its not clear how to use ansi color in sphinx. It would help if i can have some more documentation. I see this relies on https://pythonhosted.org/sphinxcontrib-ansi/index.html#sphinxcontrib.ansi but i can't seem to find this project on bitbucket and seems like this project. I am not sure if this project ceased development. How can i work around getting ansi color in sphinx so its rendered properly. If not i need way to disable coloring or apply some sed scripts to strip them out

**Comment by jamadden** [comment]
The URL `` https://pythonhosted.org/sphinxcontrib-programoutput/#confval-programoutput_use_ansi `` is outdated (I didn't even realize it was still around); documentation has lived at https://sphinxcontrib-programoutput.readthedocs.io/en/latest/ for several years now.

[Release 0.9 of this project from 2017](https://sphinxcontrib-programoutput.readthedocs.io/en/latest/#id8) removed support for `programoutput_use_ansi` because the `sphinxcontrib.ansi` extension is no longer available on PyPI.

I have no solution to offer for trying to render ANSI color escapes.

**Comment by shahzebsiddiqui** [comment]
No worries I saw the changelog and saw this was removed. I have disabled color coding when generating documentation since I figured this extension is not working. It would be good to either remove this webpage or add this feature. It is confusing for reader that this feature is enabled but in reality it is not supported.

**Comment by ssbarnea** [comment]
@shahzebsiddiqui There is a fork at https://github.com/sphinx-contrib/sphinxcontrib-programoutput that aims to add support for ANSI but is not ready, only some very limited ANSI support is working with that one. I failed to find time to finish the work on it.

**Comment by henryiii** [comment]
Note that Python 3.14 is adding support for color output in `--help`, so there will be more color output in 3.14+.
